name: ship_env
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.1=2
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - certifi==2017.4.17
  - chardet==3.0.4
  - decorator==4.0.11
  - flake8==3.3.0
  - idna==2.5
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - jedi==0.10.2
  - mccabe==0.6.1
  - nose==1.3.7
  - oauthlib==2.0.2
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.14
  - ptyprocess==0.5.2
  - pycodestyle==2.3.1
  - pyflakes==1.5.0
  - pygments==2.2.0
  - requests==2.18.1
  - requests-oauthlib==0.8.0
  - simplegeneric==0.8.1
  - six==1.10.0
  - traitlets==4.3.2
  - tweepy==3.5.0
  - urllib3==1.21.1
  - wcwidth==0.1.7

